name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]   # Runs daily
  workflow_dispatch:                # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PrajwalK01
          config_timezone: Asia/Kolkata
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins enabled
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_streak: yes
          plugin_habits: yes
          plugin_achievements: yes
